### ISSUE TITLE
Unable to import nispor

### ISSUE THREAD

**Issue by nakul-shahdadpuri** [nispor/nispor#99]
Hello, I was trying to work with the python version of the package but was unable to import it into the shell. 

```sh
>>> import nispor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/natkoul/.local/lib/python3.8/site-packages/nispor/__init__.py", line 20, in <module>
    from .clib_wrapper import NisporError
  File "/home/natkoul/.local/lib/python3.8/site-packages/nispor/clib_wrapper.py", line 21, in <module>
    lib.nispor_net_state_retrieve.restype = c_int
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 386, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib64/python3.8/ctypes/__init__.py", line 391, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: python: undefined symbol: nispor_net_state_retrieve
```

**Comment by michaelph** [comment]
Idem.

**Comment by cathay4t** [comment]
If you still have problem getting it down. Please provider reproduce step. Thanks!
